---
title: "Central Limit Theorem Presentation"
author: "Katie Dunning"
date: "2025-01-13"
Computing ID: umu5hh
output: html_document
---

## Central Limit Theorem

#### When sampling the distribution of sample means, as the sample size (n) increases, the data will take on a more normal distribution.  This will be the case even if the distribution is a shape other than normal, such as binomial.

```{r BinomandNormalHist, echo=FALSE}
library(ggplot2)

# Set seed for reproducibility
set.seed(123)

# Generate random data for different n values
samplenum <- 1000

# Add random binomial and normal data for n = 20
binomdat1 <- rbinom(samplenum, size = 20, prob = 0.5)
normdat1 <- rnorm(samplenum, mean = 10, sd = 2)

# Add random binomial and normal data for n = 50
binomdat2 <- rbinom(samplenum, size = 50, prob = 0.5)
normdat2 <- rnorm(samplenum, mean = 25, sd = 3)

# Add random binomial and normal data for n = 200
binomdat3 <- rbinom(samplenum, size = 200, prob = 0.5)
normdat3 <- rnorm(samplenum, mean = 100, sd = 7)

# Create dataframe 1, dataframe 2, and dataframe 3
dataframe1 <- data.frame(
  Numbers = c(binomdat1, normdat1),
  Source = rep(c("Binomial", "Normal"), each = samplenum),
  nsize = factor("n = 20", levels = c("n = 20", "n = 50", "n = 200"))
)

dataframe2 <- data.frame(
  Numbers = c(binomdat2, normdat2),
  Source = rep(c("Binomial", "Normal"), each = samplenum),
  nsize = factor("n = 50", levels = c("n = 20", "n = 50", "n = 200"))
)

dataframe3 <- data.frame(
  Numbers = c(binomdat3, normdat3),
  Source = rep(c("Binomial", "Normal"), each = samplenum),
  nsize = factor("n = 200", levels = c("n = 20", "n = 50", "n = 200"))
)

# Combine all dataframes.
combineframe <- rbind(dataframe1, dataframe2, dataframe3)

# Make the histogram utilizing ggplot and density.
ggplot(combineframe, aes(x = Numbers, fill = Source)) +
  geom_histogram(aes(y = after_stat(density)),
                 alpha = 0.5,
                 position = "identity",
                 bins = 30) +
  geom_density(aes(color = Source),
               alpha = 0.2) +
  facet_wrap(~nsize, scales = "free") +
  theme_minimal() +
  labs(title = "Binomial and Normal Distributions n=20, 50, 200",
       x = "Numbers",
       y = "Density") +
  scale_fill_brewer(palette = "Set2") +
  scale_color_brewer(palette = "Set2")
```

Viewing these histograms together, you can see that the n=20 histogram diverges the most.  This is partially because n under 30 will have a less pronounced change towards normal.  The change in the "n=50" histogram is apparent, with a much smoother curve that is beginning to mimic the shape of the normal data curve.  The final histogram of "n=200" shows that at larger n values, the graph curves are very closely overlapping each other.

Reference:
Central limit theorem: Definition and examples. Statistics How To. (n.d.). https://www.statisticshowto.com/probability-and-statistics/normal-distributions/central-limit-theorem-definition-examples/ 
